name: Build and release for Windows

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag / release name (e.g. v1.2.3). If empty, uses auto-<sha>"
        required: false
        default: ""
      platforms:
        description: "Comma-separated platforms to build. Default: windows/amd64"
        required: false
        default: "windows/amd64"

permissions:
  contents: write

jobs:
  windows-build-and-release:
    runs-on: windows-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          cache: "true"

      - name: Determine release tag
        id: tag
        shell: powershell
        run: |
          if ("${{ github.event.inputs.tag }}" -ne "") {
            $t = "${{ github.event.inputs.tag }}"
          } else {
            $t = "auto-$($env:GITHUB_SHA.Substring(0,8))"
          }
          # write lowercase "tag" output
          "tag=$t" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Prepare MSVC environment (capture env)
        shell: powershell
        run: |
          Write-Host "Locating Visual Studio (vswhere)..."
          $vswhere = Join-Path ${Env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
          if (-not (Test-Path $vswhere)) {
            throw "vswhere.exe not found at $vswhere; runner should have Visual Studio Build Tools installed."
          }
          $instPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          if (-not $instPath) {
            throw "No suitable Visual Studio installation found."
          }
          Write-Host "Found VS at: $instPath"
          # prefer vcvars64 if present, else VsDevCmd
          $vcvars = Join-Path $instPath "VC\Auxiliary\Build\vcvars64.bat"
          if (-not (Test-Path $vcvars)) {
            $vcvars = Join-Path $instPath "Common7\Tools\VsDevCmd.bat"
          }
          if (-not (Test-Path $vcvars)) {
            throw "vcvars script not found under $instPath"
          }
          Write-Host "Using vcvars script: $vcvars"
          # run vcvars and capture environment in env.txt
          & cmd /c "`"$vcvars`" && set" > env.txt
          Write-Host "Captured VC environment to env.txt"

      - name: Import VC environment & set Go env
        shell: powershell
        run: |
          $lines = Get-Content env.txt
          foreach ($l in $lines) {
            if ($l -match "=") {
              $parts = $l -split "=",2
              # set in-process so subsequent steps use them
              [System.Environment]::SetEnvironmentVariable($parts[0], $parts[1], "Process")
            }
          }

          # sanity checks
          Write-Host "Checking for cl.exe..."
          $cl = Get-Command cl.exe -ErrorAction SilentlyContinue
          if ($null -ne $cl) {
            Write-Host ("cl.exe found at: " + $cl.Source)
          } else {
            throw "cl.exe not found in PATH; vcvars import likely failed."
          }

          Write-Host "go version:"
          go version
          Write-Host "go env:"
          go env

      - name: Download modules
        shell: powershell
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          $env:CGO_ENABLED = "1"
          Write-Host "Downloading modules..."
          go mod tidy -v
          go mod download -v

      - name: Build binaries (Windows amd64)
        shell: powershell
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          $env:CGO_ENABLED = "1"
          New-Item -ItemType Directory -Path out -Force | Out-Null
          Write-Host "Building tailscaled.exe..."
          go build -v -o out\tailscaled-windows-amd64.exe ./cmd/tailscaled
          Write-Host "Building tailscale.exe..."
          go build -v -o out\tailscale-windows-amd64.exe ./cmd/tailscale

      - name: GH Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          body: |
            Automated Windows build from commit ${{ github.sha }}.
          files: |
            out/tailscaled-windows-amd64.exe
            out/tailscale-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to workflow run
        uses: actions/upload-artifact@v5
        with:
          name: windows-artifacts-${{ steps.tag.outputs.tag }}
          path: out/*
